=== sbluhm/spacewalk-support/rpmbuild/BUILD/simple-core-3.1.3/doc/dtd/mapper.dtd
<!--
  mapper.dtd May 2005
 
  Copyright (C) 2005, Niall Gallagher <niallg@users.sf.net>
 
  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation.
 
  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
  GNU Lesser General Public License for more details.
 
  You should have received a copy of the GNU Lesser General 
  Public License along with this library; if not, write to the 
  Free Software Foundation, Inc., 59 Temple Place, Suite 330, 
  Boston, MA  02111-1307  USA
-->

<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT mapper (resolve*)>

<!ELEMENT resolve (#PCDATA)>

<!ATTLIST resolve match CDATA #REQUIRED name CDATA #REQUIRED type CDATA #REQUIRED>

=== sbluhm/spacewalk-support/rpmbuild/BUILDROOT/simple-core-3.1.3-10.el8.x86_64/usr/share/javadoc/simple-core-3.1.3/example/mapper.xml
<?xml version="1.0"?>
<!DOCTYPE mapper SYSTEM "http://www.simpleframework.org/dtd/mapper.dtd">
<mapper>

   <resolve match="/*" name="testFile1" type="simple.test.TestFile1"/>
   <resolve match="*/" name="testFile2" type="simple.test.TestFile2"/>
   <resolve match="/*.vm" name="testDisplay1" type="simple.test.TestDisplay1"/>
   <resolve match="/*.VM" name="testDisplay1" type="simple.test.TestDisplay1"/>
   <resolve match="/*.groovy" name="testDisplay1" type="simple.test.TestDisplay1"/>
   <resolve match="/*.GROOVY" name="testDisplay1" type="simple.test.TestDisplay1"/>
   <resolve match="/*.do" name="testDisplay2" type="simple.test.TestDisplay2"/>
   <resolve match="/redirect1/*" name="testRedirect1" type="simple.test.TestRedirect1"/>
   <resolve match="/redirect2/*" name="testRedirect2" type="simple.test.TestRedirect2"/>
   <resolve match="/redirect3/*" name="testRedirect3" type="simple.test.TestRedirect3"/>
   <resolve match="/source/*" name="testSource1" type="simple.test.TestSource1"/>

</mapper>
